// <auto-generated />
using System;
using ClickRabbitERP_Testing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClickRabbitERP_Testing.Migrations
{
    [DbContext(typeof(ERPDbContext))]
    [Migration("20211120130639_all")]
    partial class all
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.CustomerViewModel", b =>
                {
                    b.Property<int>("CompID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Activationdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creationdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalesOrderModelSOID")
                        .HasColumnType("int");

                    b.HasKey("CompID");

                    b.HasIndex("SalesOrderModelSOID");

                    b.ToTable("CustomerMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.Item", b =>
                {
                    b.Property<int>("ProductCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CGST")
                        .HasColumnType("real");

                    b.Property<int>("CatagoryCode")
                        .HasColumnType("int");

                    b.Property<int>("HSNCode")
                        .HasColumnType("int");

                    b.Property<float>("ManufactureDiscount")
                        .HasColumnType("real");

                    b.Property<string>("MenuFacturerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLicenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseOrderModelPOID")
                        .HasColumnType("int");

                    b.Property<float>("SGST")
                        .HasColumnType("real");

                    b.Property<int?>("SalesOrderModelSOID")
                        .HasColumnType("int");

                    b.Property<float>("TradePrice")
                        .HasColumnType("real");

                    b.HasKey("ProductCode");

                    b.HasIndex("CatagoryCode");

                    b.HasIndex("PurchaseOrderModelPOID");

                    b.HasIndex("SalesOrderModelSOID");

                    b.ToTable("ItemMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.ItemCategoryModel", b =>
                {
                    b.Property<int>("CatgID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CatgName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CatgID");

                    b.ToTable("ItemCategoryMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.PurchaseLineModel", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CGST")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocLineNumber")
                        .HasColumnType("int");

                    b.Property<int>("PostedQty")
                        .HasColumnType("int");

                    b.Property<float>("ProducrPrice")
                        .HasColumnType("real");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToPost")
                        .HasColumnType("int");

                    b.Property<int>("SGST")
                        .HasColumnType("int");

                    b.Property<int>("SourceNumber")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("SourceNumber");

                    b.ToTable("PurchaseLineMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.PurchaseOrderModel", b =>
                {
                    b.Property<int>("POID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.Property<string>("VendorInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("POID");

                    b.ToTable("PurchaseOrderMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.SalesLineModel", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CGST")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocLineNumber")
                        .HasColumnType("int");

                    b.Property<int>("PostedQty")
                        .HasColumnType("int");

                    b.Property<float>("ProducrPrice")
                        .HasColumnType("real");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToPost")
                        .HasColumnType("int");

                    b.Property<int>("SGST")
                        .HasColumnType("int");

                    b.Property<int>("SourceNumber")
                        .HasColumnType("int");

                    b.HasKey("TransactionID");

                    b.HasIndex("SourceNumber");

                    b.ToTable("SalesLineMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.SalesOrderModel", b =>
                {
                    b.Property<int>("SOID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesOrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SOID");

                    b.ToTable("SalesOrderMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.VendorViewModel", b =>
                {
                    b.Property<int>("CompID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Activationdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Compphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creationdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchaseOrderModelPOID")
                        .HasColumnType("int");

                    b.Property<string>("RelType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompID");

                    b.HasIndex("PurchaseOrderModelPOID");

                    b.ToTable("VendorMaster");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.CustomerViewModel", b =>
                {
                    b.HasOne("ClickRabbitERP_Testing.Models.SalesOrderModel", null)
                        .WithMany("Customers")
                        .HasForeignKey("SalesOrderModelSOID");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.Item", b =>
                {
                    b.HasOne("ClickRabbitERP_Testing.Models.ItemCategoryModel", "catgid")
                        .WithMany()
                        .HasForeignKey("CatagoryCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClickRabbitERP_Testing.Models.PurchaseOrderModel", null)
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderModelPOID");

                    b.HasOne("ClickRabbitERP_Testing.Models.SalesOrderModel", null)
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderModelSOID");

                    b.Navigation("catgid");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.PurchaseLineModel", b =>
                {
                    b.HasOne("ClickRabbitERP_Testing.Models.PurchaseOrderModel", "PurchaseOrderNo")
                        .WithMany("PurchaseLines")
                        .HasForeignKey("SourceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrderNo");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.SalesLineModel", b =>
                {
                    b.HasOne("ClickRabbitERP_Testing.Models.SalesOrderModel", "SalesOrderNumber")
                        .WithMany("SalesLines")
                        .HasForeignKey("SourceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrderNumber");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.VendorViewModel", b =>
                {
                    b.HasOne("ClickRabbitERP_Testing.Models.PurchaseOrderModel", null)
                        .WithMany("Vendors")
                        .HasForeignKey("PurchaseOrderModelPOID");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.PurchaseOrderModel", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("PurchaseLines");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("ClickRabbitERP_Testing.Models.SalesOrderModel", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Items");

                    b.Navigation("SalesLines");
                });
#pragma warning restore 612, 618
        }
    }
}
